{
 "title": "Hosts - Nix",
 "templating": {
  "list": [
   {
    "name": "hosts",
    "query": {
     "query": "label_values(up{job=\"hosts\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$hosts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "hosts" },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum((node_time_seconds{instance=\"$hosts\",job=\"hosts\"} - node_boot_time_seconds{instance=\"$hosts\",job=\"hosts\"}) OR vector(0))",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Root disk usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (node_filesystem_size_bytes{instance=\"$hosts\",mountpoint=\"/\"} - node_filesystem_free_bytes{instance=\"$hosts\",mountpoint=\"/\"} > 0)",
     "legendFormat": "Used Space"
    },
    {
     "expr": "avg by (instance) (node_filesystem_size_bytes{instance=\"$hosts\",mountpoint=\"/\"} > 0)",
     "legendFormat": "Total Space"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=\"$hosts\"} - node_memory_MemAvailable_bytes{instance=\"$hosts\"} or vector(0))",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$hosts\"}",
     "legendFormat": "Total Memory"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - rate(node_cpu_seconds_total{mode=\"idle\",instance=\"$hosts\"}[1m])",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Last Upgrade",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum((time() - (node_systemd_timer_last_trigger_seconds{name=\"nixos-upgrade.timer\",instance=\"$hosts\"} > 0)) or vector(0))",
     "legendFormat": "Last Upgrade"
    }
   ]
  }
 ]
}